insert into users (user_name, email, user_password) values ('Marys Shipway', 'mshipway0@tripadvisor.com', 'function');
insert into users (user_name, email, user_password) values ('Flor Slaght', 'fslaght1@mayoclinic.com', 'high-level');
insert into users (user_name, email, user_password) values ('Nikolas Silmon', 'nsilmon2@bravesites.com', 'Ergonomic');
insert into users (user_name, email, user_password) values ('Emory Tottle', 'etottle3@live.com', 'human-resource');
insert into users (user_name, email, user_password) values ('Sonni Redolfi', 'sredolfi4@over-blog.com', '5th generation');
insert into users (user_name, email, user_password) values ('Rory Flew', 'rflew5@example.com', 'moderator');
insert into users (user_name, email, user_password) values ('Ricca Robbings', 'rrobbings6@alibaba.com', 'composite');
insert into users (user_name, email, user_password) values ('Rene Bunyan', 'rbunyan7@mayoclinic.com', 'bottom-line');
insert into users (user_name, email, user_password) values ('Peyter Schild', 'pschild8@opensource.org', 'human-resource');
insert into users (user_name, email, user_password) values ('Bunnie Buterton', 'bbuterton9@acquirethisname.com', 'value-added');
insert into users (user_name, email, user_password) values ('Wilona Brugmann', 'wbrugmanna@jiathis.com', 'grid-enabled');
insert into users (user_name, email, user_password) values ('Stanislaus Trapp', 'strappb@webnode.com', 'Public-key');
insert into users (user_name, email, user_password) values ('Ema Olczak', 'eolczakc@dell.com', '24/7');
insert into users (user_name, email, user_password) values ('Fons Flobert', 'fflobertd@deliciousdays.com', 'Focused');
insert into users (user_name, email, user_password) values ('Jacqueline Husselbee', 'jhusselbeee@tripod.com', 'Intuitive');
insert into users (user_name, email, user_password) values ('Alyssa Cahn', 'acahnf@walmart.com', 'initiative');
insert into users (user_name, email, user_password) values ('Barnebas Rippingale', 'brippingaleg@php.net', 'framework');
insert into users (user_name, email, user_password) values ('Vinni Yaxley', 'vyaxleyh@nymag.com', 'Monitored');
insert into users (user_name, email, user_password) values ('Siward Royson', 'sroysoni@google.fr', 'hub');
insert into users (user_name, email, user_password) values ('Humberto Emmens', 'hemmensj@csmonitor.com', 'Up-sized');
insert into users (user_name, email, user_password) values ('Marina Mulvy', 'mmulvyk@istockphoto.com', 'motivating');
insert into users (user_name, email, user_password) values ('Jolyn Spileman', 'jspilemanl@gizmodo.com', 'attitude-oriented');
insert into users (user_name, email, user_password) values ('Doralia Mcsarry', 'dmcsarrym@shop-pro.jp', 'Intuitive');
insert into users (user_name, email, user_password) values ('Lacee Scandroot', 'lscandrootn@vinaora.com', 'Versatile');
insert into users (user_name, email, user_password) values ('Salmon Bryning', 'sbryningo@google.it', 'multi-tasking');
insert into users (user_name, email, user_password) values ('Angelle Oleksiak', 'aoleksiakp@squarespace.com', 'data-warehouse');
insert into users (user_name, email, user_password) values ('Sonia Cawthorne', 'scawthorneq@deliciousdays.com', 'Cross-platform');
insert into users (user_name, email, user_password) values ('Berkly Murrow', 'bmurrowr@wikia.com', 'algorithm');
insert into users (user_name, email, user_password) values ('Tabina Bolesworth', 'tbolesworths@pcworld.com', 'firmware');
insert into users (user_name, email, user_password) values ('Kaitlynn Iskov', 'kiskovt@irs.gov', 'discrete');
insert into users (user_name, email, user_password) values ('Marylinda Rack', 'mracku@ihg.com', 'non-volatile');
insert into users (user_name, email, user_password) values ('Halsy Ashfield', 'hashfieldv@bloomberg.com', 'Self-enabling');
insert into users (user_name, email, user_password) values ('Druci Cranstone', 'dcranstonew@nationalgeographic.com', 'implementation');
insert into users (user_name, email, user_password) values ('Bronnie Cuthbertson', 'bcuthbertsonx@trellian.com', 'Inverse');
insert into users (user_name, email, user_password) values ('Devondra Hamelyn', 'dhamelyny@miitbeian.gov.cn', 'uniform');
insert into users (user_name, email, user_password) values ('Rosella Asbery', 'rasberyz@timesonline.co.uk', 'bandwidth-monitored');
insert into users (user_name, email, user_password) values ('Marybeth Milhench', 'mmilhench10@hc360.com', 'encompassing');
insert into users (user_name, email, user_password) values ('Wolfy Carmichael', 'wcarmichael11@seattletimes.com', 'didactic');
insert into users (user_name, email, user_password) values ('Kora Swanger', 'kswanger12@washington.edu', 'multimedia');
insert into users (user_name, email, user_password) values ('Grace McCole', 'gmccole13@unc.edu', 'Polarised');
insert into users (user_name, email, user_password) values ('Grete Troppmann', 'gtroppmann14@acquirethisname.com', 'real-time');
insert into users (user_name, email, user_password) values ('Abbot Corten', 'acorten15@amazon.com', 'customer loyalty');
insert into users (user_name, email, user_password) values ('Adriane Mcasparan', 'amcasparan16@unc.edu', 'even-keeled');
insert into users (user_name, email, user_password) values ('Floris Chaperling', 'fchaperling17@t-online.de', 'intangible');
insert into users (user_name, email, user_password) values ('Codi Nore', 'cnore18@walmart.com', 'Face to face');
insert into users (user_name, email, user_password) values ('Lars Daughtrey', 'ldaughtrey19@abc.net.au', 'Seamless');
insert into users (user_name, email, user_password) values ('Livy Paddemore', 'lpaddemore1a@wikia.com', 'logistical');
insert into users (user_name, email, user_password) values ('Eugenie McGlaughn', 'emcglaughn1b@foxnews.com', 'system-worthy');
insert into users (user_name, email, user_password) values ('Oren Inman', 'oinman1c@prnewswire.com', 'solution-oriented');
insert into users (user_name, email, user_password) values ('Mella Walkowski', 'mwalkowski1d@cbc.ca', 'Pre-emptive');
insert into users (user_name, email, user_password) values ('Brody Cloonan', 'bcloonan1e@ifeng.com', 'adapter');
insert into users (user_name, email, user_password) values ('Sally Hagger', 'shagger1f@bandcamp.com', 'discrete');
insert into users (user_name, email, user_password) values ('Glenda McPhail', 'gmcphail1g@istockphoto.com', 'capability');
insert into users (user_name, email, user_password) values ('Alis Gandley', 'agandley1h@yellowbook.com', 'explicit');
insert into users (user_name, email, user_password) values ('Jesse Tooting', 'jtooting1i@yolasite.com', 'Synergized');
insert into users (user_name, email, user_password) values ('Yvonne Panchen', 'ypanchen1j@tamu.edu', 'system engine');
insert into users (user_name, email, user_password) values ('Beatrice Fullwood', 'bfullwood1k@issuu.com', 'bi-directional');
insert into users (user_name, email, user_password) values ('Arlena Hullin', 'ahullin1l@paginegialle.it', 'Triple-buffered');
insert into users (user_name, email, user_password) values ('Aryn Moynham', 'amoynham1m@ftc.gov', 'disintermediate');
insert into users (user_name, email, user_password) values ('Welsh Druce', 'wdruce1n@timesonline.co.uk', 'middleware');
insert into users (user_name, email, user_password) values ('Iolande Swait', 'iswait1o@sciencedirect.com', 'Progressive');
insert into users (user_name, email, user_password) values ('Worden Fiddy', 'wfiddy1p@globo.com', 'toolset');
insert into users (user_name, email, user_password) values ('Biddie Farre', 'bfarre1q@sogou.com', 'knowledge base');
insert into users (user_name, email, user_password) values ('Ethelind Tomczykowski', 'etomczykowski1r@globo.com', 'extranet');
insert into users (user_name, email, user_password) values ('Warren Newstead', 'wnewstead1s@ucoz.com', 'synergy');
insert into users (user_name, email, user_password) values ('Kayla Hibbart', 'khibbart1t@miitbeian.gov.cn', 'intangible');
insert into users (user_name, email, user_password) values ('Frank McPhee', 'fmcphee1u@wikimedia.org', 'Quality-focused');
insert into users (user_name, email, user_password) values ('Eran Abbe', 'eabbe1v@sitemeter.com', 'local');
insert into users (user_name, email, user_password) values ('Woodman Spilsbury', 'wspilsbury1w@gmpg.org', 'De-engineered');
insert into users (user_name, email, user_password) values ('Consolata Gideon', 'cgideon1x@shareasale.com', 'task-force');
insert into users (user_name, email, user_password) values ('Ignatius Lambole', 'ilambole1y@hhs.gov', 'clear-thinking');
insert into users (user_name, email, user_password) values ('Sammy Wyne', 'swyne1z@cornell.edu', 'Customer-focused');
insert into users (user_name, email, user_password) values ('Zed Toffanini', 'ztoffanini20@yelp.com', 'standardization');
insert into users (user_name, email, user_password) values ('Jobye Bellham', 'jbellham21@sbwire.com', 'Cross-group');
insert into users (user_name, email, user_password) values ('Melba Niblo', 'mniblo22@dot.gov', 'Quality-focused');
insert into users (user_name, email, user_password) values ('Orella Ribey', 'oribey23@slashdot.org', 'Synchronised');
insert into users (user_name, email, user_password) values ('Edin Birdsey', 'ebirdsey24@mysql.com', 'Mandatory');
insert into users (user_name, email, user_password) values ('Nick Gothup', 'ngothup25@elpais.com', 'dedicated');
insert into users (user_name, email, user_password) values ('Phoebe Shinn', 'pshinn26@wikispaces.com', 'Triple-buffered');
insert into users (user_name, email, user_password) values ('Janot Dingley', 'jdingley27@whitehouse.gov', 'encoding');
insert into users (user_name, email, user_password) values ('Dietrich Lavington', 'dlavington28@tinyurl.com', 'neutral');
insert into users (user_name, email, user_password) values ('Mendy Crippell', 'mcrippell29@zimbio.com', 'Managed');
insert into users (user_name, email, user_password) values ('Mikael Cordie', 'mcordie2a@springer.com', 'bandwidth-monitored');
insert into users (user_name, email, user_password) values ('Chevy Gorghetto', 'cgorghetto2b@clickbank.net', 'Visionary');
insert into users (user_name, email, user_password) values ('Minnaminnie Root', 'mroot2c@wix.com', 'radical');
insert into users (user_name, email, user_password) values ('Jourdan Haveline', 'jhaveline2d@washington.edu', 'concept');
insert into users (user_name, email, user_password) values ('Doralynn McKag', 'dmckag2e@sina.com.cn', 'discrete');
insert into users (user_name, email, user_password) values ('Lothaire Basezzi', 'lbasezzi2f@blogger.com', 'De-engineered');
insert into users (user_name, email, user_password) values ('Michale Pavek', 'mpavek2g@networksolutions.com', 'throughput');
insert into users (user_name, email, user_password) values ('Tibold Crippin', 'tcrippin2h@lycos.com', 'Innovative');
insert into users (user_name, email, user_password) values ('Colas Wraight', 'cwraight2i@phoca.cz', 'architecture');
insert into users (user_name, email, user_password) values ('Rachael Stockhill', 'rstockhill2j@msn.com', 'project');
insert into users (user_name, email, user_password) values ('Kaspar Morecomb', 'kmorecomb2k@delicious.com', 'value-added');
insert into users (user_name, email, user_password) values ('Berget MacKeever', 'bmackeever2l@home.pl', 'Organized');
insert into users (user_name, email, user_password) values ('Moritz Puttergill', 'mputtergill2m@istockphoto.com', 'optimizing');
insert into users (user_name, email, user_password) values ('Alano Moorton', 'amoorton2n@tripadvisor.com', 'budgetary management');
insert into users (user_name, email, user_password) values ('Roanne Pittle', 'rpittle2o@infoseek.co.jp', 'Quality-focused');
insert into users (user_name, email, user_password) values ('Julio Abramino', 'jabramino2p@yandex.ru', 'grid-enabled');
insert into users (user_name, email, user_password) values ('Corrie Drezzer', 'cdrezzer2q@about.me', 'task-force');
insert into users (user_name, email, user_password) values ('Maryjo Hoggins', 'mhoggins2r@fc2.com', 'Re-contextualized');


insert into meals (user_id) values (25);
insert into meals (user_id) values (64);
insert into meals (user_id) values (76);
insert into meals (user_id) values (82);
insert into meals (user_id) values (92);
insert into meals (user_id) values (89);
insert into meals (user_id) values (33);
insert into meals (user_id) values (6);
insert into meals (user_id) values (77);
insert into meals (user_id) values (42);
insert into meals (user_id) values (92);
insert into meals (user_id) values (62);
insert into meals (user_id) values (40);
insert into meals (user_id) values (28);
insert into meals (user_id) values (77);
insert into meals (user_id) values (69);
insert into meals (user_id) values (3);
insert into meals (user_id) values (87);
insert into meals (user_id) values (35);
insert into meals (user_id) values (82);
insert into meals (user_id) values (59);
insert into meals (user_id) values (49);
insert into meals (user_id) values (16);
insert into meals (user_id) values (100);
insert into meals (user_id) values (30);
insert into meals (user_id) values (48);
insert into meals (user_id) values (32);
insert into meals (user_id) values (81);
insert into meals (user_id) values (76);
insert into meals (user_id) values (47);
insert into meals (user_id) values (32);
insert into meals (user_id) values (69);
insert into meals (user_id) values (71);
insert into meals (user_id) values (28);
insert into meals (user_id) values (2);
insert into meals (user_id) values (96);
insert into meals (user_id) values (89);
insert into meals (user_id) values (93);
insert into meals (user_id) values (8);
insert into meals (user_id) values (54);
insert into meals (user_id) values (63);
insert into meals (user_id) values (7);
insert into meals (user_id) values (45);
insert into meals (user_id) values (44);
insert into meals (user_id) values (78);
insert into meals (user_id) values (48);
insert into meals (user_id) values (86);
insert into meals (user_id) values (21);
insert into meals (user_id) values (90);
insert into meals (user_id) values (38);
insert into meals (user_id) values (53);
insert into meals (user_id) values (15);
insert into meals (user_id) values (36);
insert into meals (user_id) values (34);
insert into meals (user_id) values (68);
insert into meals (user_id) values (11);
insert into meals (user_id) values (97);
insert into meals (user_id) values (18);
insert into meals (user_id) values (52);
insert into meals (user_id) values (14);
insert into meals (user_id) values (72);
insert into meals (user_id) values (25);
insert into meals (user_id) values (61);
insert into meals (user_id) values (26);
insert into meals (user_id) values (46);
insert into meals (user_id) values (3);
insert into meals (user_id) values (81);
insert into meals (user_id) values (5);
insert into meals (user_id) values (52);
insert into meals (user_id) values (100);
insert into meals (user_id) values (8);
insert into meals (user_id) values (10);
insert into meals (user_id) values (88);
insert into meals (user_id) values (87);
insert into meals (user_id) values (30);
insert into meals (user_id) values (94);
insert into meals (user_id) values (18);
insert into meals (user_id) values (38);
insert into meals (user_id) values (73);
insert into meals (user_id) values (32);
insert into meals (user_id) values (96);
insert into meals (user_id) values (81);
insert into meals (user_id) values (93);
insert into meals (user_id) values (46);
insert into meals (user_id) values (89);
insert into meals (user_id) values (65);
insert into meals (user_id) values (32);
insert into meals (user_id) values (80);
insert into meals (user_id) values (69);
insert into meals (user_id) values (67);
insert into meals (user_id) values (69);
insert into meals (user_id) values (16);
insert into meals (user_id) values (86);
insert into meals (user_id) values (28);
insert into meals (user_id) values (81);
insert into meals (user_id) values (12);
insert into meals (user_id) values (20);
insert into meals (user_id) values (62);
insert into meals (user_id) values (69);
insert into meals (user_id) values (49);

insert into ingredients (product, nut_info) values ('Evaporated Milk - Skim', '{"calories":826,"carbohydrates":11,"fiber":43,"protein":13,"fats":89}');
insert into ingredients (product, nut_info) values ('Yogurt - Cherry, 175 Gr', '{"calories":658,"carbohydrates":52,"fiber":98,"protein":45,"fats":59}');
insert into ingredients (product, nut_info) values ('Vodka - Moskovskaya', '{"calories":325,"carbohydrates":41,"fiber":72,"protein":33,"fats":15}');
insert into ingredients (product, nut_info) values ('Cake Sheet Combo Party Pack', '{"calories":128,"carbohydrates":47,"fiber":23,"protein":20,"fats":86}');
insert into ingredients (product, nut_info) values ('Water - Mineral, Natural', '{"calories":833,"carbohydrates":36,"fiber":76,"protein":66,"fats":63}');
insert into ingredients (product, nut_info) values ('Pasta - Ravioli', '{"calories":56,"carbohydrates":32,"fiber":29,"protein":18,"fats":31}');
insert into ingredients (product, nut_info) values ('Pork - Back Ribs', '{"calories":701,"carbohydrates":88,"fiber":7,"protein":61,"fats":84}');
insert into ingredients (product, nut_info) values ('Garlic - Elephant', '{"calories":160,"carbohydrates":40,"fiber":26,"protein":47,"fats":49}');
insert into ingredients (product, nut_info) values ('Chocolate Bar - Coffee Crisp', '{"calories":834,"carbohydrates":27,"fiber":47,"protein":47,"fats":61}');
insert into ingredients (product, nut_info) values ('Beer - Labatt Blue', '{"calories":968,"carbohydrates":71,"fiber":60,"protein":95,"fats":31}');
insert into ingredients (product, nut_info) values ('Bananas', '{"calories":889,"carbohydrates":26,"fiber":93,"protein":59,"fats":8}');
insert into ingredients (product, nut_info) values ('Pepper - Julienne, Frozen', '{"calories":974,"carbohydrates":27,"fiber":36,"protein":33,"fats":98}');
insert into ingredients (product, nut_info) values ('Eggs - Extra Large', '{"calories":699,"carbohydrates":78,"fiber":2,"protein":38,"fats":63}');
insert into ingredients (product, nut_info) values ('Cheese - Brick With Pepper', '{"calories":759,"carbohydrates":37,"fiber":10,"protein":88,"fats":54}');
insert into ingredients (product, nut_info) values ('Soup Campbells Turkey Veg.', '{"calories":784,"carbohydrates":86,"fiber":11,"protein":83,"fats":43}');
insert into ingredients (product, nut_info) values ('Mustard - Pommery', '{"calories":493,"carbohydrates":47,"fiber":3,"protein":36,"fats":100}');
insert into ingredients (product, nut_info) values ('Pepper - Julienne, Frozen', '{"calories":149,"carbohydrates":24,"fiber":75,"protein":39,"fats":94}');
insert into ingredients (product, nut_info) values ('Salmon - Smoked, Sliced', '{"calories":918,"carbohydrates":17,"fiber":98,"protein":90,"fats":96}');
insert into ingredients (product, nut_info) values ('Rolled Oats', '{"calories":704,"carbohydrates":3,"fiber":81,"protein":3,"fats":58}');
insert into ingredients (product, nut_info) values ('Mushroom - White Button', '{"calories":535,"carbohydrates":85,"fiber":50,"protein":19,"fats":70}');
insert into ingredients (product, nut_info) values ('Sambuca - Opal Nera', '{"calories":869,"carbohydrates":56,"fiber":29,"protein":56,"fats":31}');
insert into ingredients (product, nut_info) values ('Wild Boar - Tenderloin', '{"calories":314,"carbohydrates":92,"fiber":67,"protein":86,"fats":10}');
insert into ingredients (product, nut_info) values ('Apple - Northern Spy', '{"calories":198,"carbohydrates":3,"fiber":96,"protein":91,"fats":97}');
insert into ingredients (product, nut_info) values ('Milk - 1%', '{"calories":325,"carbohydrates":21,"fiber":97,"protein":35,"fats":22}');
insert into ingredients (product, nut_info) values ('Onions - Vidalia', '{"calories":236,"carbohydrates":17,"fiber":55,"protein":11,"fats":100}');
insert into ingredients (product, nut_info) values ('Carroway Seed', '{"calories":455,"carbohydrates":30,"fiber":2,"protein":43,"fats":17}');
insert into ingredients (product, nut_info) values ('Devonshire Cream', '{"calories":760,"carbohydrates":1,"fiber":96,"protein":15,"fats":48}');
insert into ingredients (product, nut_info) values ('Crab Brie In Phyllo', '{"calories":386,"carbohydrates":21,"fiber":61,"protein":68,"fats":28}');
insert into ingredients (product, nut_info) values ('Cheese - Marble', '{"calories":418,"carbohydrates":36,"fiber":21,"protein":2,"fats":93}');
insert into ingredients (product, nut_info) values ('Lamb Leg - Bone - In Nz', '{"calories":988,"carbohydrates":10,"fiber":34,"protein":43,"fats":62}');
insert into ingredients (product, nut_info) values ('Crackers - Soda / Saltins', '{"calories":632,"carbohydrates":4,"fiber":19,"protein":44,"fats":48}');
insert into ingredients (product, nut_info) values ('Vodka - Hot, Lnferno', '{"calories":903,"carbohydrates":36,"fiber":35,"protein":73,"fats":44}');
insert into ingredients (product, nut_info) values ('Chicken - Soup Base', '{"calories":533,"carbohydrates":16,"fiber":53,"protein":60,"fats":68}');
insert into ingredients (product, nut_info) values ('Beef - Texas Style Burger', '{"calories":696,"carbohydrates":86,"fiber":30,"protein":54,"fats":85}');
insert into ingredients (product, nut_info) values ('Lamb - Whole Head Off', '{"calories":743,"carbohydrates":95,"fiber":31,"protein":31,"fats":8}');
insert into ingredients (product, nut_info) values ('Sugar - Icing', '{"calories":909,"carbohydrates":39,"fiber":8,"protein":27,"fats":55}');
insert into ingredients (product, nut_info) values ('Ecolab - Hand Soap Form Antibac', '{"calories":539,"carbohydrates":47,"fiber":31,"protein":31,"fats":16}');
insert into ingredients (product, nut_info) values ('Beans - Soya Bean', '{"calories":543,"carbohydrates":26,"fiber":100,"protein":79,"fats":71}');
insert into ingredients (product, nut_info) values ('Lamb - Loin Chops', '{"calories":942,"carbohydrates":82,"fiber":90,"protein":24,"fats":99}');
insert into ingredients (product, nut_info) values ('Ecolab Silver Fusion', '{"calories":49,"carbohydrates":98,"fiber":20,"protein":55,"fats":100}');
insert into ingredients (product, nut_info) values ('Soup - Campbells Mushroom', '{"calories":763,"carbohydrates":2,"fiber":63,"protein":5,"fats":55}');
insert into ingredients (product, nut_info) values ('Chicken - Bones', '{"calories":39,"carbohydrates":15,"fiber":60,"protein":10,"fats":31}');
insert into ingredients (product, nut_info) values ('Shrimp - Black Tiger 8 - 12', '{"calories":109,"carbohydrates":35,"fiber":16,"protein":43,"fats":94}');
insert into ingredients (product, nut_info) values ('Pork - Belly Fresh', '{"calories":910,"carbohydrates":93,"fiber":58,"protein":91,"fats":6}');
insert into ingredients (product, nut_info) values ('Bread - Corn Muffaleta Onion', '{"calories":311,"carbohydrates":14,"fiber":20,"protein":27,"fats":84}');
insert into ingredients (product, nut_info) values ('Pur Source', '{"calories":608,"carbohydrates":77,"fiber":72,"protein":32,"fats":58}');
insert into ingredients (product, nut_info) values ('Wine - Chateau Aqueria Tavel', '{"calories":756,"carbohydrates":80,"fiber":88,"protein":87,"fats":30}');
insert into ingredients (product, nut_info) values ('Piping Jelly - All Colours', '{"calories":931,"carbohydrates":6,"fiber":94,"protein":77,"fats":21}');
insert into ingredients (product, nut_info) values ('Grenadine', '{"calories":336,"carbohydrates":13,"fiber":80,"protein":37,"fats":31}');
insert into ingredients (product, nut_info) values ('Bread - White Mini Epi', '{"calories":535,"carbohydrates":45,"fiber":18,"protein":49,"fats":100}');
insert into ingredients (product, nut_info) values ('Jam - Blackberry, 20 Ml Jar', '{"calories":141,"carbohydrates":17,"fiber":86,"protein":93,"fats":18}');
insert into ingredients (product, nut_info) values ('Beer - Pilsner Urquell', '{"calories":549,"carbohydrates":26,"fiber":26,"protein":47,"fats":29}');
insert into ingredients (product, nut_info) values ('Bread - Pumpernickle, Rounds', '{"calories":694,"carbohydrates":72,"fiber":46,"protein":44,"fats":75}');
insert into ingredients (product, nut_info) values ('Pepper - Red Chili', '{"calories":123,"carbohydrates":15,"fiber":67,"protein":6,"fats":49}');
insert into ingredients (product, nut_info) values ('Ecolab - Ster Bac', '{"calories":718,"carbohydrates":26,"fiber":64,"protein":36,"fats":12}');
insert into ingredients (product, nut_info) values ('Country Roll', '{"calories":103,"carbohydrates":23,"fiber":24,"protein":51,"fats":46}');
insert into ingredients (product, nut_info) values ('Mushroom - Portebello', '{"calories":320,"carbohydrates":49,"fiber":68,"protein":31,"fats":42}');
insert into ingredients (product, nut_info) values ('Pie Pecan', '{"calories":908,"carbohydrates":30,"fiber":3,"protein":62,"fats":24}');
insert into ingredients (product, nut_info) values ('Tuna - Yellowfin', '{"calories":53,"carbohydrates":6,"fiber":24,"protein":83,"fats":55}');
insert into ingredients (product, nut_info) values ('Doilies - 10, Paper', '{"calories":312,"carbohydrates":18,"fiber":52,"protein":69,"fats":99}');
insert into ingredients (product, nut_info) values ('Tortillas - Flour, 12', '{"calories":124,"carbohydrates":66,"fiber":75,"protein":41,"fats":35}');
insert into ingredients (product, nut_info) values ('Okra', '{"calories":474,"carbohydrates":22,"fiber":36,"protein":16,"fats":13}');
insert into ingredients (product, nut_info) values ('Bread - Italian Sesame Poly', '{"calories":267,"carbohydrates":22,"fiber":52,"protein":43,"fats":1}');
insert into ingredients (product, nut_info) values ('Veal - Tenderloin, Untrimmed', '{"calories":396,"carbohydrates":18,"fiber":3,"protein":41,"fats":57}');
insert into ingredients (product, nut_info) values ('Pie Filling - Pumpkin', '{"calories":603,"carbohydrates":35,"fiber":47,"protein":88,"fats":76}');
insert into ingredients (product, nut_info) values ('Potatoes - Idaho 100 Count', '{"calories":993,"carbohydrates":42,"fiber":49,"protein":88,"fats":8}');
insert into ingredients (product, nut_info) values ('Chef Hat 25cm', '{"calories":384,"carbohydrates":98,"fiber":93,"protein":60,"fats":8}');
insert into ingredients (product, nut_info) values ('Carbonated Water - Strawberry', '{"calories":173,"carbohydrates":5,"fiber":21,"protein":21,"fats":89}');
insert into ingredients (product, nut_info) values ('Oil - Pumpkinseed', '{"calories":875,"carbohydrates":50,"fiber":85,"protein":100,"fats":94}');
insert into ingredients (product, nut_info) values ('Soup - Campbells, Chix Gumbo', '{"calories":613,"carbohydrates":93,"fiber":52,"protein":93,"fats":21}');
insert into ingredients (product, nut_info) values ('Island Oasis - Pina Colada', '{"calories":134,"carbohydrates":30,"fiber":76,"protein":58,"fats":67}');
insert into ingredients (product, nut_info) values ('Nantucket - Pomegranate Pear', '{"calories":479,"carbohydrates":26,"fiber":77,"protein":29,"fats":44}');
insert into ingredients (product, nut_info) values ('Cake - French Pear Tart', '{"calories":286,"carbohydrates":3,"fiber":87,"protein":31,"fats":18}');
insert into ingredients (product, nut_info) values ('Sauce - Black Current, Dry Mix', '{"calories":806,"carbohydrates":52,"fiber":100,"protein":99,"fats":29}');
insert into ingredients (product, nut_info) values ('Shrimp - 21/25, Peel And Deviened', '{"calories":621,"carbohydrates":100,"fiber":21,"protein":92,"fats":56}');
insert into ingredients (product, nut_info) values ('Flower - Daisies', '{"calories":153,"carbohydrates":43,"fiber":57,"protein":7,"fats":41}');
insert into ingredients (product, nut_info) values ('Wine - Marlbourough Sauv Blanc', '{"calories":879,"carbohydrates":71,"fiber":80,"protein":43,"fats":48}');
insert into ingredients (product, nut_info) values ('Soup - Knorr, Veg / Beef', '{"calories":982,"carbohydrates":49,"fiber":25,"protein":8,"fats":11}');
insert into ingredients (product, nut_info) values ('Peas - Frozen', '{"calories":95,"carbohydrates":60,"fiber":44,"protein":89,"fats":81}');
insert into ingredients (product, nut_info) values ('Ginger - Fresh', '{"calories":47,"carbohydrates":5,"fiber":45,"protein":19,"fats":99}');
insert into ingredients (product, nut_info) values ('Nut - Almond, Blanched, Ground', '{"calories":997,"carbohydrates":44,"fiber":49,"protein":74,"fats":44}');
insert into ingredients (product, nut_info) values ('Lemonade - Island Tea, 591 Ml', '{"calories":997,"carbohydrates":75,"fiber":68,"protein":33,"fats":59}');
insert into ingredients (product, nut_info) values ('Propel Sport Drink', '{"calories":359,"carbohydrates":94,"fiber":92,"protein":39,"fats":77}');
insert into ingredients (product, nut_info) values ('Oats Large Flake', '{"calories":195,"carbohydrates":85,"fiber":30,"protein":100,"fats":24}');
insert into ingredients (product, nut_info) values ('Appetizer - Cheese Bites', '{"calories":56,"carbohydrates":7,"fiber":70,"protein":68,"fats":76}');
insert into ingredients (product, nut_info) values ('Cheese - Havarti, Salsa', '{"calories":336,"carbohydrates":70,"fiber":77,"protein":67,"fats":76}');
insert into ingredients (product, nut_info) values ('Muffin Hinge - 211n', '{"calories":417,"carbohydrates":58,"fiber":41,"protein":18,"fats":26}');
insert into ingredients (product, nut_info) values ('Rambutan', '{"calories":565,"carbohydrates":30,"fiber":90,"protein":84,"fats":52}');
insert into ingredients (product, nut_info) values ('V8 - Tropical Blend', '{"calories":313,"carbohydrates":19,"fiber":2,"protein":96,"fats":82}');
insert into ingredients (product, nut_info) values ('Numi - Assorted Teas', '{"calories":696,"carbohydrates":78,"fiber":58,"protein":58,"fats":35}');
insert into ingredients (product, nut_info) values ('Salmon - Atlantic, Fresh, Whole', '{"calories":215,"carbohydrates":88,"fiber":24,"protein":8,"fats":44}');
insert into ingredients (product, nut_info) values ('Sole - Fillet', '{"calories":998,"carbohydrates":8,"fiber":4,"protein":55,"fats":44}');
insert into ingredients (product, nut_info) values ('Roe - Flying Fish', '{"calories":256,"carbohydrates":2,"fiber":60,"protein":20,"fats":79}');
insert into ingredients (product, nut_info) values ('Muffin Hinge Container 6', '{"calories":746,"carbohydrates":85,"fiber":64,"protein":56,"fats":21}');
insert into ingredients (product, nut_info) values ('Beef - Ground, Extra Lean, Fresh', '{"calories":407,"carbohydrates":38,"fiber":28,"protein":37,"fats":29}');
insert into ingredients (product, nut_info) values ('Kahlua', '{"calories":643,"carbohydrates":11,"fiber":76,"protein":100,"fats":60}');
insert into ingredients (product, nut_info) values ('Bread Crumbs - Japanese Style', '{"calories":490,"carbohydrates":59,"fiber":18,"protein":9,"fats":23}');
insert into ingredients (product, nut_info) values ('Cream Of Tartar', '{"calories":891,"carbohydrates":100,"fiber":24,"protein":39,"fats":46}');
insert into ingredients (product, nut_info) values ('Soup - Campbells Pasta Fagioli', '{"calories":427,"carbohydrates":83,"fiber":85,"protein":26,"fats":17}');
insert into ingredients (product, nut_info) values ('Cookies - Englishbay Oatmeal', '{"calories":815,"carbohydrates":12,"fiber":39,"protein":65,"fats":68}');


insert into favorites (user_id, meal_id) values (55, 30);
insert into favorites (user_id, meal_id) values (47, 87);
insert into favorites (user_id, meal_id) values (98, 6);
insert into favorites (user_id, meal_id) values (78, 53);
insert into favorites (user_id, meal_id) values (65, 98);
insert into favorites (user_id, meal_id) values (81, 10);
insert into favorites (user_id, meal_id) values (1, 56);
insert into favorites (user_id, meal_id) values (61, 30);
insert into favorites (user_id, meal_id) values (90, 87);
insert into favorites (user_id, meal_id) values (23, 35);
insert into favorites (user_id, meal_id) values (10, 36);
insert into favorites (user_id, meal_id) values (30, 56);
insert into favorites (user_id, meal_id) values (47, 65);
insert into favorites (user_id, meal_id) values (40, 69);
insert into favorites (user_id, meal_id) values (99, 78);
insert into favorites (user_id, meal_id) values (50, 25);
insert into favorites (user_id, meal_id) values (93, 96);
insert into favorites (user_id, meal_id) values (47, 8);
insert into favorites (user_id, meal_id) values (82, 60);
insert into favorites (user_id, meal_id) values (21, 54);
insert into favorites (user_id, meal_id) values (8, 8);
insert into favorites (user_id, meal_id) values (69, 51);
insert into favorites (user_id, meal_id) values (7, 75);
insert into favorites (user_id, meal_id) values (67, 47);
insert into favorites (user_id, meal_id) values (51, 6);
insert into favorites (user_id, meal_id) values (67, 93);
insert into favorites (user_id, meal_id) values (57, 20);
insert into favorites (user_id, meal_id) values (32, 23);
insert into favorites (user_id, meal_id) values (36, 59);
insert into favorites (user_id, meal_id) values (39, 64);
insert into favorites (user_id, meal_id) values (63, 59);
insert into favorites (user_id, meal_id) values (64, 94);
insert into favorites (user_id, meal_id) values (97, 31);
insert into favorites (user_id, meal_id) values (17, 99);
insert into favorites (user_id, meal_id) values (80, 100);
insert into favorites (user_id, meal_id) values (99, 60);
insert into favorites (user_id, meal_id) values (18, 19);
insert into favorites (user_id, meal_id) values (79, 7);
insert into favorites (user_id, meal_id) values (31, 8);
insert into favorites (user_id, meal_id) values (72, 15);
insert into favorites (user_id, meal_id) values (80, 100);
insert into favorites (user_id, meal_id) values (14, 22);
insert into favorites (user_id, meal_id) values (89, 75);
insert into favorites (user_id, meal_id) values (10, 62);
insert into favorites (user_id, meal_id) values (51, 93);
insert into favorites (user_id, meal_id) values (87, 49);
insert into favorites (user_id, meal_id) values (42, 76);
insert into favorites (user_id, meal_id) values (45, 27);
insert into favorites (user_id, meal_id) values (46, 35);
insert into favorites (user_id, meal_id) values (19, 82);
insert into favorites (user_id, meal_id) values (79, 59);
insert into favorites (user_id, meal_id) values (18, 32);
insert into favorites (user_id, meal_id) values (91, 17);
insert into favorites (user_id, meal_id) values (53, 47);
insert into favorites (user_id, meal_id) values (99, 56);
insert into favorites (user_id, meal_id) values (56, 20);
insert into favorites (user_id, meal_id) values (81, 93);
insert into favorites (user_id, meal_id) values (23, 6);
insert into favorites (user_id, meal_id) values (79, 30);
insert into favorites (user_id, meal_id) values (68, 84);
insert into favorites (user_id, meal_id) values (47, 9);
insert into favorites (user_id, meal_id) values (49, 38);
insert into favorites (user_id, meal_id) values (72, 68);
insert into favorites (user_id, meal_id) values (67, 89);
insert into favorites (user_id, meal_id) values (68, 99);
insert into favorites (user_id, meal_id) values (78, 35);
insert into favorites (user_id, meal_id) values (11, 13);
insert into favorites (user_id, meal_id) values (13, 65);
insert into favorites (user_id, meal_id) values (80, 1);
insert into favorites (user_id, meal_id) values (23, 29);
insert into favorites (user_id, meal_id) values (41, 62);
insert into favorites (user_id, meal_id) values (45, 85);
insert into favorites (user_id, meal_id) values (55, 80);
insert into favorites (user_id, meal_id) values (6, 14);
insert into favorites (user_id, meal_id) values (81, 95);
insert into favorites (user_id, meal_id) values (65, 8);
insert into favorites (user_id, meal_id) values (31, 48);
insert into favorites (user_id, meal_id) values (81, 74);
insert into favorites (user_id, meal_id) values (1, 88);
insert into favorites (user_id, meal_id) values (90, 24);
insert into favorites (user_id, meal_id) values (61, 33);
insert into favorites (user_id, meal_id) values (49, 43);
insert into favorites (user_id, meal_id) values (58, 94);
insert into favorites (user_id, meal_id) values (92, 83);
insert into favorites (user_id, meal_id) values (61, 50);
insert into favorites (user_id, meal_id) values (97, 33);
insert into favorites (user_id, meal_id) values (49, 80);
insert into favorites (user_id, meal_id) values (31, 94);
insert into favorites (user_id, meal_id) values (27, 100);
insert into favorites (user_id, meal_id) values (66, 29);
insert into favorites (user_id, meal_id) values (41, 22);
insert into favorites (user_id, meal_id) values (29, 31);
insert into favorites (user_id, meal_id) values (29, 99);
insert into favorites (user_id, meal_id) values (36, 12);
insert into favorites (user_id, meal_id) values (9, 80);
insert into favorites (user_id, meal_id) values (6, 30);
insert into favorites (user_id, meal_id) values (58, 91);
insert into favorites (user_id, meal_id) values (59, 88);
insert into favorites (user_id, meal_id) values (79, 25);
insert into favorites (user_id, meal_id) values (74, 55);

insert into meal_photos (meal_id, image_url) values (98, 'http://dummyimage.com/132x171.jpg/ff4444/ffffff');
insert into meal_photos (meal_id, image_url) values (17, 'http://dummyimage.com/202x219.jpg/cc0000/ffffff');
insert into meal_photos (meal_id, image_url) values (83, 'http://dummyimage.com/243x243.jpg/dddddd/000000');
insert into meal_photos (meal_id, image_url) values (43, 'http://dummyimage.com/175x124.jpg/cc0000/ffffff');
insert into meal_photos (meal_id, image_url) values (26, 'http://dummyimage.com/171x225.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (48, 'http://dummyimage.com/177x186.jpg/ff4444/ffffff');
insert into meal_photos (meal_id, image_url) values (19, 'http://dummyimage.com/237x156.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (45, 'http://dummyimage.com/118x192.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (47, 'http://dummyimage.com/210x126.jpg/dddddd/000000');
insert into meal_photos (meal_id, image_url) values (38, 'http://dummyimage.com/187x162.jpg/dddddd/000000');
insert into meal_photos (meal_id, image_url) values (41, 'http://dummyimage.com/163x146.jpg/dddddd/000000');
insert into meal_photos (meal_id, image_url) values (5, 'http://dummyimage.com/223x216.jpg/cc0000/ffffff');
insert into meal_photos (meal_id, image_url) values (62, 'http://dummyimage.com/206x204.jpg/cc0000/ffffff');
insert into meal_photos (meal_id, image_url) values (80, 'http://dummyimage.com/166x160.jpg/ff4444/ffffff');
insert into meal_photos (meal_id, image_url) values (46, 'http://dummyimage.com/134x213.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (28, 'http://dummyimage.com/183x108.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (79, 'http://dummyimage.com/110x190.jpg/dddddd/000000');
insert into meal_photos (meal_id, image_url) values (26, 'http://dummyimage.com/204x176.jpg/cc0000/ffffff');
insert into meal_photos (meal_id, image_url) values (97, 'http://dummyimage.com/190x129.jpg/cc0000/ffffff');
insert into meal_photos (meal_id, image_url) values (83, 'http://dummyimage.com/250x242.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (28, 'http://dummyimage.com/144x111.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (56, 'http://dummyimage.com/156x145.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (66, 'http://dummyimage.com/150x132.jpg/dddddd/000000');
insert into meal_photos (meal_id, image_url) values (52, 'http://dummyimage.com/195x222.jpg/cc0000/ffffff');
insert into meal_photos (meal_id, image_url) values (33, 'http://dummyimage.com/190x108.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (64, 'http://dummyimage.com/211x138.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (99, 'http://dummyimage.com/108x170.jpg/ff4444/ffffff');
insert into meal_photos (meal_id, image_url) values (39, 'http://dummyimage.com/114x207.jpg/cc0000/ffffff');
insert into meal_photos (meal_id, image_url) values (45, 'http://dummyimage.com/156x110.jpg/dddddd/000000');
insert into meal_photos (meal_id, image_url) values (93, 'http://dummyimage.com/201x140.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (53, 'http://dummyimage.com/213x122.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (55, 'http://dummyimage.com/234x202.jpg/dddddd/000000');
insert into meal_photos (meal_id, image_url) values (88, 'http://dummyimage.com/132x157.jpg/dddddd/000000');
insert into meal_photos (meal_id, image_url) values (99, 'http://dummyimage.com/242x174.jpg/dddddd/000000');
insert into meal_photos (meal_id, image_url) values (28, 'http://dummyimage.com/239x111.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (49, 'http://dummyimage.com/244x213.jpg/ff4444/ffffff');
insert into meal_photos (meal_id, image_url) values (48, 'http://dummyimage.com/246x170.jpg/dddddd/000000');
insert into meal_photos (meal_id, image_url) values (3, 'http://dummyimage.com/106x119.jpg/ff4444/ffffff');
insert into meal_photos (meal_id, image_url) values (26, 'http://dummyimage.com/156x213.jpg/cc0000/ffffff');
insert into meal_photos (meal_id, image_url) values (97, 'http://dummyimage.com/145x175.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (53, 'http://dummyimage.com/243x103.jpg/dddddd/000000');
insert into meal_photos (meal_id, image_url) values (71, 'http://dummyimage.com/175x244.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (49, 'http://dummyimage.com/147x164.jpg/dddddd/000000');
insert into meal_photos (meal_id, image_url) values (20, 'http://dummyimage.com/231x100.jpg/ff4444/ffffff');
insert into meal_photos (meal_id, image_url) values (15, 'http://dummyimage.com/238x249.jpg/ff4444/ffffff');
insert into meal_photos (meal_id, image_url) values (28, 'http://dummyimage.com/203x119.jpg/cc0000/ffffff');
insert into meal_photos (meal_id, image_url) values (61, 'http://dummyimage.com/235x122.jpg/ff4444/ffffff');
insert into meal_photos (meal_id, image_url) values (8, 'http://dummyimage.com/135x149.jpg/dddddd/000000');
insert into meal_photos (meal_id, image_url) values (16, 'http://dummyimage.com/174x151.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (90, 'http://dummyimage.com/149x148.jpg/cc0000/ffffff');
insert into meal_photos (meal_id, image_url) values (53, 'http://dummyimage.com/130x215.jpg/dddddd/000000');
insert into meal_photos (meal_id, image_url) values (15, 'http://dummyimage.com/195x227.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (11, 'http://dummyimage.com/155x246.jpg/cc0000/ffffff');
insert into meal_photos (meal_id, image_url) values (62, 'http://dummyimage.com/222x195.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (49, 'http://dummyimage.com/224x173.jpg/ff4444/ffffff');
insert into meal_photos (meal_id, image_url) values (55, 'http://dummyimage.com/172x222.jpg/dddddd/000000');
insert into meal_photos (meal_id, image_url) values (50, 'http://dummyimage.com/174x181.jpg/dddddd/000000');
insert into meal_photos (meal_id, image_url) values (56, 'http://dummyimage.com/141x108.jpg/dddddd/000000');
insert into meal_photos (meal_id, image_url) values (29, 'http://dummyimage.com/132x168.jpg/cc0000/ffffff');
insert into meal_photos (meal_id, image_url) values (53, 'http://dummyimage.com/122x186.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (35, 'http://dummyimage.com/156x200.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (29, 'http://dummyimage.com/240x189.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (96, 'http://dummyimage.com/149x145.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (19, 'http://dummyimage.com/236x111.jpg/dddddd/000000');
insert into meal_photos (meal_id, image_url) values (65, 'http://dummyimage.com/109x191.jpg/ff4444/ffffff');
insert into meal_photos (meal_id, image_url) values (81, 'http://dummyimage.com/131x240.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (24, 'http://dummyimage.com/216x167.jpg/ff4444/ffffff');
insert into meal_photos (meal_id, image_url) values (37, 'http://dummyimage.com/133x181.jpg/cc0000/ffffff');
insert into meal_photos (meal_id, image_url) values (27, 'http://dummyimage.com/163x163.jpg/ff4444/ffffff');
insert into meal_photos (meal_id, image_url) values (21, 'http://dummyimage.com/168x100.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (34, 'http://dummyimage.com/178x132.jpg/dddddd/000000');
insert into meal_photos (meal_id, image_url) values (22, 'http://dummyimage.com/159x157.jpg/dddddd/000000');
insert into meal_photos (meal_id, image_url) values (100, 'http://dummyimage.com/134x124.jpg/dddddd/000000');
insert into meal_photos (meal_id, image_url) values (81, 'http://dummyimage.com/248x200.jpg/dddddd/000000');
insert into meal_photos (meal_id, image_url) values (48, 'http://dummyimage.com/145x126.jpg/dddddd/000000');
insert into meal_photos (meal_id, image_url) values (46, 'http://dummyimage.com/145x167.jpg/ff4444/ffffff');
insert into meal_photos (meal_id, image_url) values (26, 'http://dummyimage.com/102x232.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (95, 'http://dummyimage.com/128x174.jpg/ff4444/ffffff');
insert into meal_photos (meal_id, image_url) values (18, 'http://dummyimage.com/230x164.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (98, 'http://dummyimage.com/123x143.jpg/dddddd/000000');
insert into meal_photos (meal_id, image_url) values (25, 'http://dummyimage.com/155x235.jpg/dddddd/000000');
insert into meal_photos (meal_id, image_url) values (36, 'http://dummyimage.com/178x144.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (76, 'http://dummyimage.com/148x217.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (50, 'http://dummyimage.com/142x234.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (3, 'http://dummyimage.com/136x141.jpg/cc0000/ffffff');
insert into meal_photos (meal_id, image_url) values (44, 'http://dummyimage.com/214x240.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (68, 'http://dummyimage.com/160x170.jpg/ff4444/ffffff');
insert into meal_photos (meal_id, image_url) values (68, 'http://dummyimage.com/134x174.jpg/cc0000/ffffff');
insert into meal_photos (meal_id, image_url) values (93, 'http://dummyimage.com/160x197.jpg/ff4444/ffffff');
insert into meal_photos (meal_id, image_url) values (78, 'http://dummyimage.com/200x173.jpg/dddddd/000000');
insert into meal_photos (meal_id, image_url) values (91, 'http://dummyimage.com/141x239.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (76, 'http://dummyimage.com/133x206.jpg/ff4444/ffffff');
insert into meal_photos (meal_id, image_url) values (85, 'http://dummyimage.com/184x110.jpg/ff4444/ffffff');
insert into meal_photos (meal_id, image_url) values (19, 'http://dummyimage.com/191x109.jpg/ff4444/ffffff');
insert into meal_photos (meal_id, image_url) values (80, 'http://dummyimage.com/188x237.jpg/ff4444/ffffff');
insert into meal_photos (meal_id, image_url) values (21, 'http://dummyimage.com/156x129.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (89, 'http://dummyimage.com/202x227.jpg/dddddd/000000');
insert into meal_photos (meal_id, image_url) values (39, 'http://dummyimage.com/102x226.jpg/dddddd/000000');
insert into meal_photos (meal_id, image_url) values (70, 'http://dummyimage.com/158x192.jpg/5fa2dd/ffffff');
insert into meal_photos (meal_id, image_url) values (36, 'http://dummyimage.com/134x140.jpg/cc0000/ffffff');

insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (43, 94, 5);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (89, 72, 2);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (37, 58, 2);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (9, 42, 4);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (18, 78, 7);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (71, 22, 9);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (55, 18, 4);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (84, 29, 3);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (27, 79, 10);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (69, 27, 2);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (43, 32, 9);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (35, 44, 1);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (46, 10, 5);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (74, 80, 6);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (61, 53, 6);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (31, 85, 5);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (69, 40, 4);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (39, 8, 10);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (3, 80, 1);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (32, 8, 7);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (3, 58, 7);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (40, 54, 8);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (38, 25, 6);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (20, 37, 6);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (79, 12, 7);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (5, 11, 3);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (30, 46, 7);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (41, 49, 7);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (63, 18, 2);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (91, 8, 4);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (46, 14, 7);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (96, 34, 5);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (8, 82, 4);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (98, 17, 10);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (53, 52, 2);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (45, 57, 4);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (29, 98, 1);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (70, 84, 8);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (53, 31, 5);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (89, 74, 5);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (33, 27, 4);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (96, 61, 8);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (84, 93, 8);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (40, 67, 5);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (50, 93, 9);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (54, 17, 6);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (75, 31, 5);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (92, 40, 5);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (80, 34, 10);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (100, 19, 2);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (94, 31, 10);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (100, 87, 1);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (32, 52, 7);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (20, 95, 7);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (49, 3, 10);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (67, 28, 10);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (57, 33, 1);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (62, 71, 1);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (61, 61, 7);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (82, 90, 10);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (50, 73, 4);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (95, 53, 4);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (21, 97, 10);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (14, 76, 4);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (85, 50, 10);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (31, 27, 10);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (19, 68, 2);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (59, 69, 10);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (15, 42, 9);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (3, 81, 7);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (50, 85, 3);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (54, 21, 6);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (71, 53, 5);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (88, 82, 9);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (88, 45, 6);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (100, 88, 7);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (41, 86, 4);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (76, 64, 8);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (32, 23, 10);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (95, 60, 2);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (100, 84, 2);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (49, 22, 10);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (11, 8, 3);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (95, 5, 10);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (14, 32, 6);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (51, 74, 6);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (26, 14, 7);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (34, 94, 10);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (91, 19, 8);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (74, 93, 6);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (76, 73, 8);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (5, 16, 4);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (27, 62, 3);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (76, 4, 2);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (5, 96, 1);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (22, 58, 2);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (70, 23, 1);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (34, 74, 9);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (7, 51, 2);
insert into meal_ingredients (meal_id, ingredient_id, serving_size) values (35, 56, 2);


insert into categories (category) values ('Prroshyan');
insert into categories (category) values ('Mališevo');
insert into categories (category) values ('Kumanovo');
insert into categories (category) values ('Changfu');
insert into categories (category) values ('Nynäshamn');
insert into categories (category) values ('Soledade');
insert into categories (category) values ('Xinqiao');
insert into categories (category) values ('El Olivar');
insert into categories (category) values ('Xiaxihao');
insert into categories (category) values ('Manga');
insert into categories (category) values ('Kavásilas');
insert into categories (category) values ('Charlotte');
insert into categories (category) values ('Täby');
insert into categories (category) values ('Bethlehem');
insert into categories (category) values ('Guadalupe');
insert into categories (category) values ('Dukuhturi');
insert into categories (category) values ('Sandnes');
insert into categories (category) values ('Kiszkowo');
insert into categories (category) values ('Jambean');
insert into categories (category) values ('Jacareí');
insert into categories (category) values ('Lyon');
insert into categories (category) values ('Amangarh');
insert into categories (category) values ('Tambovka');
insert into categories (category) values ('Don Mueang');
insert into categories (category) values ('Gludug');
insert into categories (category) values ('Temuji');
insert into categories (category) values ('Sinegor''ye');
insert into categories (category) values ('Tongzhong');
insert into categories (category) values ('Fenghuang');
insert into categories (category) values ('Port-Cartier');
insert into categories (category) values ('Siikainen');
insert into categories (category) values ('Guadalupe Victoria');
insert into categories (category) values ('Corujeira');
insert into categories (category) values ('Rio Branco do Sul');
insert into categories (category) values ('Kalutara');
insert into categories (category) values ('Conceição da Barra');
insert into categories (category) values ('Carusucan');
insert into categories (category) values ('Freixo de Numão');
insert into categories (category) values ('Santa Helena');
insert into categories (category) values ('Shangsanji');
insert into categories (category) values ('Madrid');
insert into categories (category) values ('Psará');
insert into categories (category) values ('Xuwei');
insert into categories (category) values ('Lijiazui');
insert into categories (category) values ('La Paz');
insert into categories (category) values ('Rasi Salai');
insert into categories (category) values ('Nishor');
insert into categories (category) values ('Kunčina');
insert into categories (category) values ('Јегуновце');
insert into categories (category) values ('Lom Kao');
insert into categories (category) values ('Ouro Preto do Oeste');
insert into categories (category) values ('Sherwood Park');
insert into categories (category) values ('Krasnokholmskiy');
insert into categories (category) values ('Al ‘Āliyah');
insert into categories (category) values ('Nijemci');
insert into categories (category) values ('Ciepielów');
insert into categories (category) values ('Port Saint Lucie');
insert into categories (category) values ('Moyynkum');
insert into categories (category) values ('Yucheng');
insert into categories (category) values ('Honiara');
insert into categories (category) values ('Poitiers');
insert into categories (category) values ('Bandaragung');
insert into categories (category) values ('Tsirang');
insert into categories (category) values ('Santa Maria');
insert into categories (category) values ('Calumpit');
insert into categories (category) values ('Bartolomé Masó');
insert into categories (category) values ('Río Alejandro');
insert into categories (category) values ('Maksatikha');
insert into categories (category) values ('Tiling');
insert into categories (category) values ('Bálsamo Oriental');
insert into categories (category) values ('Mergayu');
insert into categories (category) values ('Yong’an');
insert into categories (category) values ('Puricay');
insert into categories (category) values ('Alajuela');
insert into categories (category) values ('Pontal');
insert into categories (category) values ('Saint-Marcellin');
insert into categories (category) values ('Chiguirip');
insert into categories (category) values ('Mosal’sk');
insert into categories (category) values ('Jinggongqiao');
insert into categories (category) values ('Laranjeiras');
insert into categories (category) values ('Tasikmalaya');
insert into categories (category) values ('Lima Pampa');
insert into categories (category) values ('Lisiy Nos');
insert into categories (category) values ('Fort Worth');
insert into categories (category) values ('Kvartsitnyy');
insert into categories (category) values ('Hartswater');
insert into categories (category) values ('Bondokodi');
insert into categories (category) values ('Nowshera');
insert into categories (category) values ('Kendal');
insert into categories (category) values ('Reston');
insert into categories (category) values ('Dengzishan');
insert into categories (category) values ('Sumberbening');
insert into categories (category) values ('Yasothon');
insert into categories (category) values ('Moca');
insert into categories (category) values ('Světlá nad Sázavou');
insert into categories (category) values ('Haysyn');
insert into categories (category) values ('Rathdrum');
insert into categories (category) values ('Lingcheng');
insert into categories (category) values ('Sinarbakti');
insert into categories (category) values ('San Simón');

insert into meal_categories (meal_id, category_id) values (76, 76);
insert into meal_categories (meal_id, category_id) values (57, 90);
insert into meal_categories (meal_id, category_id) values (66, 45);
insert into meal_categories (meal_id, category_id) values (59, 27);
insert into meal_categories (meal_id, category_id) values (32, 55);
insert into meal_categories (meal_id, category_id) values (45, 40);
insert into meal_categories (meal_id, category_id) values (94, 23);
insert into meal_categories (meal_id, category_id) values (47, 46);
insert into meal_categories (meal_id, category_id) values (19, 1);
insert into meal_categories (meal_id, category_id) values (57, 27);
insert into meal_categories (meal_id, category_id) values (15, 49);
insert into meal_categories (meal_id, category_id) values (99, 16);
insert into meal_categories (meal_id, category_id) values (37, 35);
insert into meal_categories (meal_id, category_id) values (76, 7);
insert into meal_categories (meal_id, category_id) values (7, 59);
insert into meal_categories (meal_id, category_id) values (12, 35);
insert into meal_categories (meal_id, category_id) values (57, 78);
insert into meal_categories (meal_id, category_id) values (63, 58);
insert into meal_categories (meal_id, category_id) values (76, 32);
insert into meal_categories (meal_id, category_id) values (63, 91);
insert into meal_categories (meal_id, category_id) values (63, 59);
insert into meal_categories (meal_id, category_id) values (7, 75);
insert into meal_categories (meal_id, category_id) values (53, 20);
insert into meal_categories (meal_id, category_id) values (77, 94);
insert into meal_categories (meal_id, category_id) values (63, 47);
insert into meal_categories (meal_id, category_id) values (25, 67);
insert into meal_categories (meal_id, category_id) values (23, 88);
insert into meal_categories (meal_id, category_id) values (41, 68);
insert into meal_categories (meal_id, category_id) values (32, 7);
insert into meal_categories (meal_id, category_id) values (70, 22);
insert into meal_categories (meal_id, category_id) values (51, 47);
insert into meal_categories (meal_id, category_id) values (73, 55);
insert into meal_categories (meal_id, category_id) values (47, 93);
insert into meal_categories (meal_id, category_id) values (61, 98);
insert into meal_categories (meal_id, category_id) values (92, 3);
insert into meal_categories (meal_id, category_id) values (1, 54);
insert into meal_categories (meal_id, category_id) values (84, 29);
insert into meal_categories (meal_id, category_id) values (63, 82);
insert into meal_categories (meal_id, category_id) values (27, 91);
insert into meal_categories (meal_id, category_id) values (73, 9);
insert into meal_categories (meal_id, category_id) values (39, 95);
insert into meal_categories (meal_id, category_id) values (84, 23);
insert into meal_categories (meal_id, category_id) values (9, 56);
insert into meal_categories (meal_id, category_id) values (89, 47);
insert into meal_categories (meal_id, category_id) values (23, 43);
insert into meal_categories (meal_id, category_id) values (45, 33);
insert into meal_categories (meal_id, category_id) values (82, 33);
insert into meal_categories (meal_id, category_id) values (1, 10);
insert into meal_categories (meal_id, category_id) values (27, 38);
insert into meal_categories (meal_id, category_id) values (90, 24);
insert into meal_categories (meal_id, category_id) values (75, 13);
insert into meal_categories (meal_id, category_id) values (71, 78);
insert into meal_categories (meal_id, category_id) values (73, 58);
insert into meal_categories (meal_id, category_id) values (34, 20);
insert into meal_categories (meal_id, category_id) values (74, 60);
insert into meal_categories (meal_id, category_id) values (35, 87);
insert into meal_categories (meal_id, category_id) values (13, 45);
insert into meal_categories (meal_id, category_id) values (57, 29);
insert into meal_categories (meal_id, category_id) values (45, 77);
insert into meal_categories (meal_id, category_id) values (73, 75);
insert into meal_categories (meal_id, category_id) values (35, 83);
insert into meal_categories (meal_id, category_id) values (46, 19);
insert into meal_categories (meal_id, category_id) values (13, 35);
insert into meal_categories (meal_id, category_id) values (95, 44);
insert into meal_categories (meal_id, category_id) values (68, 10);
insert into meal_categories (meal_id, category_id) values (51, 3);
insert into meal_categories (meal_id, category_id) values (73, 4);
insert into meal_categories (meal_id, category_id) values (28, 44);
insert into meal_categories (meal_id, category_id) values (95, 83);
insert into meal_categories (meal_id, category_id) values (100, 5);
insert into meal_categories (meal_id, category_id) values (98, 77);
insert into meal_categories (meal_id, category_id) values (26, 57);
insert into meal_categories (meal_id, category_id) values (90, 72);
insert into meal_categories (meal_id, category_id) values (66, 88);
insert into meal_categories (meal_id, category_id) values (96, 83);
insert into meal_categories (meal_id, category_id) values (17, 35);
insert into meal_categories (meal_id, category_id) values (54, 46);
insert into meal_categories (meal_id, category_id) values (82, 97);
insert into meal_categories (meal_id, category_id) values (77, 43);
insert into meal_categories (meal_id, category_id) values (64, 96);
insert into meal_categories (meal_id, category_id) values (86, 92);
insert into meal_categories (meal_id, category_id) values (93, 62);
insert into meal_categories (meal_id, category_id) values (82, 27);
insert into meal_categories (meal_id, category_id) values (3, 23);
insert into meal_categories (meal_id, category_id) values (25, 44);
insert into meal_categories (meal_id, category_id) values (12, 10);
insert into meal_categories (meal_id, category_id) values (79, 47);
insert into meal_categories (meal_id, category_id) values (32, 73);
insert into meal_categories (meal_id, category_id) values (14, 75);
insert into meal_categories (meal_id, category_id) values (44, 33);
insert into meal_categories (meal_id, category_id) values (74, 3);
insert into meal_categories (meal_id, category_id) values (3, 23);
insert into meal_categories (meal_id, category_id) values (83, 68);
insert into meal_categories (meal_id, category_id) values (34, 41);
insert into meal_categories (meal_id, category_id) values (80, 59);
insert into meal_categories (meal_id, category_id) values (92, 63);
insert into meal_categories (meal_id, category_id) values (45, 66);
insert into meal_categories (meal_id, category_id) values (18, 91);
insert into meal_categories (meal_id, category_id) values (89, 80);
insert into meal_categories (meal_id, category_id) values (42, 79);

insert into user_preferences (user_id, is_disliked, ingredient_id) values (73, true, 82);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (80, false, 56);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (38, true, 68);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (12, false, 34);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (81, false, 44);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (21, false, 93);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (12, true, 56);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (83, true, 97);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (57, true, 84);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (26, false, 97);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (92, true, 76);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (46, true, 70);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (20, true, 66);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (9, true, 73);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (42, false, 66);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (47, false, 93);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (2, true, 78);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (65, true, 52);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (74, false, 63);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (40, true, 97);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (46, true, 87);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (93, true, 58);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (49, true, 16);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (85, true, 62);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (55, false, 45);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (99, true, 17);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (74, true, 12);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (75, true, 81);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (60, false, 36);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (6, true, 62);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (59, false, 42);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (88, false, 92);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (55, false, 40);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (61, false, 12);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (6, true, 5);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (97, false, 1);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (81, false, 21);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (27, true, 48);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (68, true, 42);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (26, true, 22);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (14, true, 72);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (64, false, 78);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (29, true, 35);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (43, false, 58);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (87, true, 85);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (2, false, 72);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (20, true, 41);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (62, false, 89);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (19, true, 77);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (58, false, 99);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (71, false, 5);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (58, false, 27);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (100, false, 91);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (2, true, 79);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (93, true, 82);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (75, true, 63);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (34, false, 25);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (87, true, 24);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (59, true, 92);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (83, false, 100);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (79, false, 50);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (76, true, 70);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (55, true, 1);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (24, true, 19);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (21, false, 40);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (62, true, 82);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (17, true, 45);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (36, false, 64);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (17, false, 72);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (50, false, 7);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (7, false, 52);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (37, false, 24);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (65, false, 43);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (89, false, 42);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (31, true, 60);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (15, false, 45);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (39, true, 76);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (8, true, 86);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (74, true, 55);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (70, true, 66);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (40, true, 57);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (21, true, 73);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (47, true, 20);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (25, false, 47);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (63, false, 25);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (47, false, 53);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (100, false, 90);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (40, false, 93);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (43, false, 35);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (78, false, 56);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (30, true, 49);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (10, true, 40);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (56, true, 40);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (33, false, 56);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (3, false, 33);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (17, true, 2);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (83, true, 78);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (6, false, 40);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (55, true, 79);
insert into user_preferences (user_id, is_disliked, ingredient_id) values (34, false, 47);

